#!/bin/bash
#author: sergio manuel salazar dos santos
#sergio.salazar.santos@gmail.com
#mobile: 916919898
#CVS: $Header$
#help improving is always welcome
#####################################################################
shopt -s -o nounset
#
declare -rx SCRIPT=${0##*/}
IFS_OLD=$IFS
#
if test -z "$BASH"; #-z
then
	printf "$SCRIPT please run this script with the BASH shell"
	exit 192
fi
RED=1
GREEN=2
echo "$(tput setaf $RED)---------------------------------------$(tput sgr0)"
control_c()
{
	exit #all is well
}
if (( $# )); 
then
	echo "$(tput setaf $RED)$0 $@$(tput sgr0)"
echo "$(tput setaf $RED)---------------------------------------$(tput sgr0)"
else
	echo "Usage: $(tput setaf $RED)$0 exe$(tput sgr0)"
	echo "ARGUMENTS MISSING !!!"
echo "$(tput setaf $RED)---------------------------------------$(tput sgr0)"
	exit
fi
trap control_c SIGINT
TERMINALDIR=$(pwd)
###################################USAGE#########################################
#example: run mame								#
#example: run grep								#
###################################USAGE#########################################
ARGS="$@"
COMMAND="$1"
COUNT=$(ls /bin /sbin /usr/bin /usr/sbin | grep ^$COMMAND$ | wc -l)
if(( $COUNT ))
then
	$ARGS
else
	./$ARGS
fi
exit #all is well
